name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.3
  flutter_credit_card: ^3.0.6
  intl: ^0.17.0
  liquid_pull_to_refresh: ^3.0.1
  image_picker: ^0.8.7+5
  permission_handler: ^10.2.0
  flutter_svg: ^2.0.6
  cloudinary: ^1.1.1
  cloudinary_public: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/rip2.png
    - images/bubbles.png
    - images/unnamed.jpg
    - images/background.png
    - icons/home-page.png
    - icons/news.png
    - icons/setting.png
    - icons/trophy.png
    - icons/home-page-colored.png
    - icons/news-colored.png
    - icons/setting-colored.png
    - icons/trophy-colored.png
    - images/arrow.png
    - images/phone.png
    - images/savewater.png
    - images/panda.jpg
    - images/planet.jpg
    - images/calendar.png
    - images/heart.png
    - images/hands-up.png
    - images/exp.jpeg
    - images/paybill.png
    - images/medd.png
    - images/statt.png
    - images/logggo-transformed.png
    - images/flesh-transformed-transformed.png
    - images/arrow-blue.png
    - images/google.png
    - images/bubble2.png
    - images/add.png
    - images/heart1.png
    - images/agenda.png
    - images/backgroundd.jpg
    - images/bag.jpeg
    - images/bin.jpg
    - images/book-water.jpg
    - images/clock.jpg
    - images/colapz.jpg
    - images/cup.jpg
    - images/douch.jpg
    - images/f2.jpg
    - images/gift cart.png
    - images/meter.jpg
    - images/portable.jpg
    - images/safia.jpg
    - images/shower-water.jpg
    - images/toilet-bank.jpg
    - images/toilet.jpg    
    - images/mastercard.png
    - images/arrow3.svg
